domain_path: D:\Fontys\MO7\SID_Multicore_Demo\platform\export\platform\sw\standalone_ps7_cortexa9_1
app_src_dir: D:\Software\AMD\2025.1\Vitis\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
lang: c
