#ifndef XPARAMETERS_H   /* prevent circular inclusions */
#define XPARAMETERS_H   /* by using protection macros */

#define XPAR_XAXIVDMA_NUM_INSTANCES 1

/* Definitions for peripheral VIDEO_AXI_VDMA */
#define XPAR_VIDEO_AXI_VDMA_COMPATIBLE "xlnx,axi-vdma-6.3"
#define XPAR_VIDEO_AXI_VDMA_BASEADDR 0x43000000
#define XPAR_VIDEO_AXI_VDMA_HIGHADDR 0x4300ffff
#define XPAR_VIDEO_AXI_VDMA_NUM_FSTORES 0x3
#define XPAR_VIDEO_AXI_VDMA_INCLUDE_MM2S 0x1
#define XPAR_VIDEO_AXI_VDMA_INCLUDE_MM2S_DRE 0x0
#define XPAR_VIDEO_AXI_VDMA_MM2S_DATA_WIDTH 0x40
#define XPAR_VIDEO_AXI_VDMA_INCLUDE_S2MM 0x0
#define XPAR_VIDEO_AXI_VDMA_INCLUDE_S2MM_DRE 0x0
#define XPAR_VIDEO_AXI_VDMA_S2MM_DATA_WIDTH 0x40
#define XPAR_VIDEO_AXI_VDMA_ENABLE_VIDPARAM_READS 0x1
#define XPAR_VIDEO_AXI_VDMA_FLUSH_FSYNC 0x1
#define XPAR_VIDEO_AXI_VDMA_FLUSH_ON_FSYNC 0x1
#define XPAR_VIDEO_AXI_VDMA_MM2S_LINEBUFFER_DEPTH 0x1000
#define XPAR_VIDEO_AXI_VDMA_S2MM_LINEBUFFER_DEPTH 0x200
#define XPAR_VIDEO_AXI_VDMA_MM2S_GENLOCK_MODE 0x0
#define XPAR_VIDEO_AXI_VDMA_S2MM_GENLOCK_MODE 0x0
#define XPAR_VIDEO_AXI_VDMA_INCLUDE_INTERNAL_GENLOCK 0x1
#define XPAR_VIDEO_AXI_VDMA_S2MM_SOF_ENABLE 0x1
#define XPAR_VIDEO_AXI_VDMA_MM2S_TDATA_WIDTH 0x18
#define XPAR_VIDEO_AXI_VDMA_S2MM_TDATA_WIDTH 0x20
#define XPAR_VIDEO_AXI_VDMA_ENABLE_DEBUG_INFO_1 0x0
#define XPAR_VIDEO_AXI_VDMA_ENABLE_DEBUG_INFO_5 0x0
#define XPAR_VIDEO_AXI_VDMA_ENABLE_DEBUG_INFO_6 0x1
#define XPAR_VIDEO_AXI_VDMA_ENABLE_DEBUG_INFO_7 0x1
#define XPAR_VIDEO_AXI_VDMA_ENABLE_DEBUG_INFO_9 0x0
#define XPAR_VIDEO_AXI_VDMA_ENABLE_DEBUG_INFO_13 0x0
#define XPAR_VIDEO_AXI_VDMA_ENABLE_DEBUG_INFO_14 0x1
#define XPAR_VIDEO_AXI_VDMA_ENABLE_DEBUG_INFO_15 0x1
#define XPAR_VIDEO_AXI_VDMA_ENABLE_DEBUG_ALL 0x0
#define XPAR_VIDEO_AXI_VDMA_ADDRWIDTH 0x20
#define XPAR_VIDEO_AXI_VDMA_ENABLE_VERT_FLIP 0x0

/* Canonical definitions for peripheral VIDEO_AXI_VDMA */
#define XPAR_XAXIVDMA_0_BASEADDR 0x43000000
#define XPAR_XAXIVDMA_0_HIGHADDR 0x4300ffff
#define XPAR_XAXIVDMA_0_ADDRWIDTH 0x20
#define XPAR_XAXIVDMA_0_COMPATIBLE "xlnx,axi-vdma-6.3"
#define XPAR_XAXIVDMA_0_ENABLE_VIDPARAM_READS 0x1
#define XPAR_XAXIVDMA_0_ENABLE_DEBUG_INFO_1 0x0
#define XPAR_XAXIVDMA_0_ENABLE_DEBUG_INFO_5 0x0
#define XPAR_XAXIVDMA_0_ENABLE_DEBUG_INFO_6 0x1
#define XPAR_XAXIVDMA_0_ENABLE_DEBUG_INFO_7 0x1
#define XPAR_XAXIVDMA_0_ENABLE_DEBUG_INFO_9 0x0
#define XPAR_XAXIVDMA_0_ENABLE_DEBUG_INFO_13 0x0
#define XPAR_XAXIVDMA_0_ENABLE_DEBUG_INFO_14 0x1
#define XPAR_XAXIVDMA_0_ENABLE_DEBUG_INFO_15 0x1
#define XPAR_XAXIVDMA_0_ENABLE_DEBUG_ALL 0x0
#define XPAR_XAXIVDMA_0_ENABLE_VERT_FLIP 0x0
#define XPAR_XAXIVDMA_0_FLUSH_FSYNC 0x1
#define XPAR_XAXIVDMA_0_FLUSH_ON_FSYNC 0x1
#define XPAR_XAXIVDMA_0_INCLUDE_MM2S 0x1
#define XPAR_XAXIVDMA_0_INCLUDE_MM2S_DRE 0x0
#define XPAR_XAXIVDMA_0_INCLUDE_S2MM 0x0
#define XPAR_XAXIVDMA_0_INCLUDE_S2MM_DRE 0x0
#define XPAR_XAXIVDMA_0_INCLUDE_INTERNAL_GENLOCK 0x1
#define XPAR_XAXIVDMA_0_MM2S_DATA_WIDTH 0x40
#define XPAR_XAXIVDMA_0_MM2S_LINEBUFFER_DEPTH 0x1000
#define XPAR_XAXIVDMA_0_MM2S_GENLOCK_MODE 0x0
#define XPAR_XAXIVDMA_0_MM2S_TDATA_WIDTH 0x18
#define XPAR_XAXIVDMA_0_NUM_FSTORES 0x3
#define XPAR_XAXIVDMA_0_S2MM_DATA_WIDTH 0x40
#define XPAR_XAXIVDMA_0_S2MM_LINEBUFFER_DEPTH 0x200
#define XPAR_XAXIVDMA_0_S2MM_GENLOCK_MODE 0x0
#define XPAR_XAXIVDMA_0_S2MM_SOF_ENABLE 0x1
#define XPAR_XAXIVDMA_0_S2MM_TDATA_WIDTH 0x20

#define XPAR_XCORESIGHTPS_DCC_NUM_INSTANCES 1

/* Definitions for peripheral CORESIGHT */
#define XPAR_CORESIGHT_COMPATIBLE "xlnx,ps7-coresight-comp-1.00.a"
#define XPAR_CORESIGHT_BASEADDR 0xf8800000
#define XPAR_CORESIGHT_HIGHADDR 0xf88fffff

/* Canonical definitions for peripheral CORESIGHT */
#define XPAR_XCORESIGHTPS_DCC_0_BASEADDR 0xf8800000
#define XPAR_XCORESIGHTPS_DCC_0_HIGHADDR 0xf88fffff
#define XPAR_XCORESIGHTPS_DCC_0_COMPATIBLE "xlnx,ps7-coresight-comp-1.00.a"

#define XPAR_XDEVCFG_NUM_INSTANCES 1

/* Definitions for peripheral DEVCFG */
#define XPAR_DEVCFG_COMPATIBLE "xlnx,zynq-devcfg-1.0"
#define XPAR_DEVCFG_BASEADDR 0xf8007000
#define XPAR_DEVCFG_HIGHADDR 0xf80070ff
#define XPAR_DEVCFG_INTERRUPTS 0x4008
#define XPAR_DEVCFG_INTERRUPT_PARENT 0xf8f01000

/* Canonical definitions for peripheral DEVCFG */
#define XPAR_XDEVCFG_0_BASEADDR 0xf8007000
#define XPAR_XDEVCFG_0_HIGHADDR 0xf80070ff
#define XPAR_XDEVCFG_0_COMPATIBLE "xlnx,zynq-devcfg-1.0"
#define XPAR_XDEVCFG_0_INTERRUPTS 0x4008
#define XPAR_XDEVCFG_0_INTERRUPT_PARENT 0xf8f01000

#define XPAR_XDMAPS_NUM_INSTANCES 1

/* Definitions for peripheral DMAC_S */
#define XPAR_DMAC_S_COMPATIBLE "arm,pl330"
#define XPAR_DMAC_S_BASEADDR 0xf8003000
#define XPAR_DMAC_S_HIGHADDR 0xf8003fff
#define XPAR_DMAC_S_INTERRUPTS 0x400d
#define XPAR_DMAC_S_INTERRUPTS_1 0x400e
#define XPAR_DMAC_S_INTERRUPTS_2 0x400f
#define XPAR_DMAC_S_INTERRUPTS_3 0x4010
#define XPAR_DMAC_S_INTERRUPTS_4 0x4011
#define XPAR_DMAC_S_INTERRUPTS_5 0x4028
#define XPAR_DMAC_S_INTERRUPTS_6 0x4029
#define XPAR_DMAC_S_INTERRUPTS_7 0x402a
#define XPAR_DMAC_S_INTERRUPTS_8 0x402b
#define XPAR_DMAC_S_INTERRUPT_PARENT 0xf8f01000

/* Canonical definitions for peripheral DMAC_S */
#define XPAR_XDMAPS_0_BASEADDR 0xf8003000
#define XPAR_XDMAPS_0_HIGHADDR 0xf8003fff
#define XPAR_XDMAPS_0_COMPATIBLE "arm,pl330"
#define XPAR_XDMAPS_0_INTERRUPTS 0x400d
#define XPAR_XDMAPS_0_INTERRUPT_PARENT 0xf8f01000

#define XPAR_XEMACPS_NUM_INSTANCES 1

/* Definitions for peripheral GEM0 */
#define XPAR_GEM0_COMPATIBLE "xlnx,zynq-gem"
#define XPAR_GEM0_BASEADDR 0xe000b000
#define XPAR_GEM0_HIGHADDR 0xe000bfff
#define XPAR_GEM0_INTERRUPTS 0x4016
#define XPAR_GEM0_INTERRUPT_PARENT 0xf8f01000
#define XPAR_GEM0_PHY_MODE "rgmii-id"

/* Canonical definitions for peripheral GEM0 */
#define XPAR_XEMACPS_0_BASEADDR 0xe000b000
#define XPAR_XEMACPS_0_HIGHADDR 0xe000bfff
#define XPAR_XEMACPS_0_COMPATIBLE "xlnx,zynq-gem"
#define XPAR_XEMACPS_0_INTERRUPTS 0x4016
#define XPAR_XEMACPS_0_INTERRUPT_PARENT 0xf8f01000
#define XPAR_XEMACPS_0_PHY_MODE "rgmii-id"

#define XPAR_XGPIO_NUM_INSTANCES 9

/* Definitions for peripheral ARDUINO_ARDUINO_INTR_EN_PINS_2_3 */
#define XPAR_ARDUINO_ARDUINO_INTR_EN_PINS_2_3_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_ARDUINO_ARDUINO_INTR_EN_PINS_2_3_BASEADDR 0x41200000
#define XPAR_ARDUINO_ARDUINO_INTR_EN_PINS_2_3_HIGHADDR 0x4120ffff
#define XPAR_ARDUINO_ARDUINO_INTR_EN_PINS_2_3_INTERRUPT_PRESENT 0x1
#define XPAR_ARDUINO_ARDUINO_INTR_EN_PINS_2_3_IS_DUAL 0x0
#define XPAR_ARDUINO_ARDUINO_INTR_EN_PINS_2_3_INTERRUPTS 0x4024
#define XPAR_FABRIC_ARDUINO_ARDUINO_INTR_EN_PINS_2_3_INTR 36
#define XPAR_ARDUINO_ARDUINO_INTR_EN_PINS_2_3_INTERRUPT_PARENT 0xf8f01000
#define XPAR_ARDUINO_ARDUINO_INTR_EN_PINS_2_3_GPIO_WIDTH 0x2

/* Canonical definitions for peripheral ARDUINO_ARDUINO_INTR_EN_PINS_2_3 */
#define XPAR_XGPIO_0_BASEADDR 0x41200000
#define XPAR_FABRIC_XGPIO_0_INTR 36
#define XPAR_XGPIO_0_HIGHADDR 0x4120ffff
#define XPAR_XGPIO_0_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_XGPIO_0_GPIO_WIDTH 0x2
#define XPAR_XGPIO_0_INTERRUPT_PRESENT 0x1
#define XPAR_XGPIO_0_IS_DUAL 0x0
#define XPAR_XGPIO_0_INTERRUPTS 0x4024
#define XPAR_XGPIO_0_INTERRUPT_PARENT 0xf8f01000

/* Definitions for peripheral ARDUINO_ARDUINO_NO_INTR_PINS */
#define XPAR_ARDUINO_ARDUINO_NO_INTR_PINS_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_ARDUINO_ARDUINO_NO_INTR_PINS_BASEADDR 0x41210000
#define XPAR_ARDUINO_ARDUINO_NO_INTR_PINS_HIGHADDR 0x4121ffff
#define XPAR_ARDUINO_ARDUINO_NO_INTR_PINS_INTERRUPT_PRESENT 0x0
#define XPAR_ARDUINO_ARDUINO_NO_INTR_PINS_IS_DUAL 0x0
#define XPAR_ARDUINO_ARDUINO_NO_INTR_PINS_GPIO_WIDTH 0x7

/* Canonical definitions for peripheral ARDUINO_ARDUINO_NO_INTR_PINS */
#define XPAR_XGPIO_1_BASEADDR 0x41210000
#define XPAR_XGPIO_1_HIGHADDR 0x4121ffff
#define XPAR_XGPIO_1_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_XGPIO_1_GPIO_WIDTH 0x7
#define XPAR_XGPIO_1_INTERRUPT_PRESENT 0x0
#define XPAR_XGPIO_1_IS_DUAL 0x0

/* Definitions for peripheral USER_LDR_GPIO */
#define XPAR_USER_LDR_GPIO_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_USER_LDR_GPIO_BASEADDR 0x41270000
#define XPAR_USER_LDR_GPIO_HIGHADDR 0x4127ffff
#define XPAR_USER_LDR_GPIO_INTERRUPT_PRESENT 0x0
#define XPAR_USER_LDR_GPIO_IS_DUAL 0x0
#define XPAR_USER_LDR_GPIO_GPIO_WIDTH 0x4

/* Canonical definitions for peripheral USER_LDR_GPIO */
#define XPAR_XGPIO_2_BASEADDR 0x41270000
#define XPAR_XGPIO_2_HIGHADDR 0x4127ffff
#define XPAR_XGPIO_2_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_XGPIO_2_GPIO_WIDTH 0x4
#define XPAR_XGPIO_2_INTERRUPT_PRESENT 0x0
#define XPAR_XGPIO_2_IS_DUAL 0x0

/* Definitions for peripheral USER_MD_GPIO */
#define XPAR_USER_MD_GPIO_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_USER_MD_GPIO_BASEADDR 0x41280000
#define XPAR_USER_MD_GPIO_HIGHADDR 0x4128ffff
#define XPAR_USER_MD_GPIO_INTERRUPT_PRESENT 0x0
#define XPAR_USER_MD_GPIO_IS_DUAL 0x0
#define XPAR_USER_MD_GPIO_GPIO_WIDTH 0x4

/* Canonical definitions for peripheral USER_MD_GPIO */
#define XPAR_XGPIO_3_BASEADDR 0x41280000
#define XPAR_XGPIO_3_HIGHADDR 0x4128ffff
#define XPAR_XGPIO_3_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_XGPIO_3_GPIO_WIDTH 0x4
#define XPAR_XGPIO_3_INTERRUPT_PRESENT 0x0
#define XPAR_XGPIO_3_IS_DUAL 0x0

/* Definitions for peripheral USER_BTNS_GPIO */
#define XPAR_USER_BTNS_GPIO_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_USER_BTNS_GPIO_BASEADDR 0x41220000
#define XPAR_USER_BTNS_GPIO_HIGHADDR 0x4122ffff
#define XPAR_USER_BTNS_GPIO_INTERRUPT_PRESENT 0x1
#define XPAR_USER_BTNS_GPIO_IS_DUAL 0x0
#define XPAR_USER_BTNS_GPIO_INTERRUPTS 0x2001
#define XPAR_FABRIC_USER_BTNS_GPIO_INTR 1
#define XPAR_USER_BTNS_GPIO_INTERRUPT_PARENT 0x41800001
#define XPAR_USER_BTNS_GPIO_GPIO_WIDTH 0x4

/* Canonical definitions for peripheral USER_BTNS_GPIO */
#define XPAR_XGPIO_4_BASEADDR 0x41220000
#define XPAR_FABRIC_XGPIO_4_INTR 1
#define XPAR_XGPIO_4_HIGHADDR 0x4122ffff
#define XPAR_XGPIO_4_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_XGPIO_4_GPIO_WIDTH 0x4
#define XPAR_XGPIO_4_INTERRUPT_PRESENT 0x1
#define XPAR_XGPIO_4_IS_DUAL 0x0
#define XPAR_XGPIO_4_INTERRUPTS 0x2001
#define XPAR_XGPIO_4_INTERRUPT_PARENT 0x41800001

/* Definitions for peripheral USER_LEDS_GPIO */
#define XPAR_USER_LEDS_GPIO_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_USER_LEDS_GPIO_BASEADDR 0x41230000
#define XPAR_USER_LEDS_GPIO_HIGHADDR 0x4123ffff
#define XPAR_USER_LEDS_GPIO_INTERRUPT_PRESENT 0x0
#define XPAR_USER_LEDS_GPIO_IS_DUAL 0x0
#define XPAR_USER_LEDS_GPIO_GPIO_WIDTH 0x4

/* Canonical definitions for peripheral USER_LEDS_GPIO */
#define XPAR_XGPIO_5_BASEADDR 0x41230000
#define XPAR_XGPIO_5_HIGHADDR 0x4123ffff
#define XPAR_XGPIO_5_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_XGPIO_5_GPIO_WIDTH 0x4
#define XPAR_XGPIO_5_INTERRUPT_PRESENT 0x0
#define XPAR_XGPIO_5_IS_DUAL 0x0

/* Definitions for peripheral USER_RGBLEDS_GPIO */
#define XPAR_USER_RGBLEDS_GPIO_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_USER_RGBLEDS_GPIO_BASEADDR 0x41240000
#define XPAR_USER_RGBLEDS_GPIO_HIGHADDR 0x4124ffff
#define XPAR_USER_RGBLEDS_GPIO_INTERRUPT_PRESENT 0x0
#define XPAR_USER_RGBLEDS_GPIO_IS_DUAL 0x0
#define XPAR_USER_RGBLEDS_GPIO_GPIO_WIDTH 0x6

/* Canonical definitions for peripheral USER_RGBLEDS_GPIO */
#define XPAR_XGPIO_6_BASEADDR 0x41240000
#define XPAR_XGPIO_6_HIGHADDR 0x4124ffff
#define XPAR_XGPIO_6_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_XGPIO_6_GPIO_WIDTH 0x6
#define XPAR_XGPIO_6_INTERRUPT_PRESENT 0x0
#define XPAR_XGPIO_6_IS_DUAL 0x0

/* Definitions for peripheral USER_SWITCHES_GPIO */
#define XPAR_USER_SWITCHES_GPIO_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_USER_SWITCHES_GPIO_BASEADDR 0x41250000
#define XPAR_USER_SWITCHES_GPIO_HIGHADDR 0x4125ffff
#define XPAR_USER_SWITCHES_GPIO_INTERRUPT_PRESENT 0x1
#define XPAR_USER_SWITCHES_GPIO_IS_DUAL 0x0
#define XPAR_USER_SWITCHES_GPIO_INTERRUPTS 0x2002
#define XPAR_FABRIC_USER_SWITCHES_GPIO_INTR 2
#define XPAR_USER_SWITCHES_GPIO_INTERRUPT_PARENT 0x41800001
#define XPAR_USER_SWITCHES_GPIO_GPIO_WIDTH 0x2

/* Canonical definitions for peripheral USER_SWITCHES_GPIO */
#define XPAR_XGPIO_7_BASEADDR 0x41250000
#define XPAR_FABRIC_XGPIO_7_INTR 2
#define XPAR_XGPIO_7_HIGHADDR 0x4125ffff
#define XPAR_XGPIO_7_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_XGPIO_7_GPIO_WIDTH 0x2
#define XPAR_XGPIO_7_INTERRUPT_PRESENT 0x1
#define XPAR_XGPIO_7_IS_DUAL 0x0
#define XPAR_XGPIO_7_INTERRUPTS 0x2002
#define XPAR_XGPIO_7_INTERRUPT_PARENT 0x41800001

/* Definitions for peripheral VIDEO_HDMI_OUT_HPD_VIDEO */
#define XPAR_VIDEO_HDMI_OUT_HPD_VIDEO_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_VIDEO_HDMI_OUT_HPD_VIDEO_BASEADDR 0x41260000
#define XPAR_VIDEO_HDMI_OUT_HPD_VIDEO_HIGHADDR 0x4126ffff
#define XPAR_VIDEO_HDMI_OUT_HPD_VIDEO_INTERRUPT_PRESENT 0x1
#define XPAR_VIDEO_HDMI_OUT_HPD_VIDEO_IS_DUAL 0x0
#define XPAR_VIDEO_HDMI_OUT_HPD_VIDEO_GPIO_WIDTH 0x1

/* Canonical definitions for peripheral VIDEO_HDMI_OUT_HPD_VIDEO */
#define XPAR_XGPIO_8_BASEADDR 0x41260000
#define XPAR_XGPIO_8_HIGHADDR 0x4126ffff
#define XPAR_XGPIO_8_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_XGPIO_8_GPIO_WIDTH 0x1
#define XPAR_XGPIO_8_INTERRUPT_PRESENT 0x1
#define XPAR_XGPIO_8_IS_DUAL 0x0

#define XPAR_XIICPS_NUM_INSTANCES 2

/* Definitions for peripheral I2C0 */
#define XPAR_I2C0_COMPATIBLE "cdns,i2c-r1p10"
#define XPAR_I2C0_BASEADDR 0xe0004000
#define XPAR_I2C0_HIGHADDR 0xe0004fff
#define XPAR_I2C0_CLOCK_FREQ 0x6750918
#define XPAR_I2C0_INTERRUPTS 0x4019
#define XPAR_I2C0_INTERRUPT_PARENT 0xf8f01000
#define XPAR_I2C0_CLOCKS 0x26

/* Canonical definitions for peripheral I2C0 */
#define XPAR_XIICPS_0_BASEADDR 0xe0004000
#define XPAR_XIICPS_0_HIGHADDR 0xe0004fff
#define XPAR_XIICPS_0_COMPATIBLE "cdns,i2c-r1p10"
#define XPAR_XIICPS_0_CLOCK_FREQ 0x6750918
#define XPAR_XIICPS_0_CLOCKS 0x26
#define XPAR_XIICPS_0_INTERRUPTS 0x4019
#define XPAR_XIICPS_0_INTERRUPT_PARENT 0xf8f01000

/* Definitions for peripheral I2C1 */
#define XPAR_I2C1_COMPATIBLE "cdns,i2c-r1p10"
#define XPAR_I2C1_BASEADDR 0xe0005000
#define XPAR_I2C1_HIGHADDR 0xe0005fff
#define XPAR_I2C1_CLOCK_FREQ 0x6750918
#define XPAR_I2C1_INTERRUPTS 0x4030
#define XPAR_I2C1_INTERRUPT_PARENT 0xf8f01000
#define XPAR_I2C1_CLOCKS 0x27

/* Canonical definitions for peripheral I2C1 */
#define XPAR_XIICPS_1_BASEADDR 0xe0005000
#define XPAR_XIICPS_1_HIGHADDR 0xe0005fff
#define XPAR_XIICPS_1_COMPATIBLE "cdns,i2c-r1p10"
#define XPAR_XIICPS_1_CLOCK_FREQ 0x6750918
#define XPAR_XIICPS_1_CLOCKS 0x27
#define XPAR_XIICPS_1_INTERRUPTS 0x4030
#define XPAR_XIICPS_1_INTERRUPT_PARENT 0xf8f01000

#define XPAR_XINTC_NUM_INSTANCES 1

/* Definitions for peripheral USER_USER_INTC */
#define XPAR_USER_USER_INTC_COMPATIBLE "xlnx,axi-intc-4.1"
#define XPAR_USER_USER_INTC_BASEADDR 0x41800000
#define XPAR_USER_USER_INTC_HIGHADDR 0x4180ffff
#define XPAR_USER_USER_INTC_KIND_OF_INTR 0x0
#define XPAR_USER_USER_INTC_IS_FAST 0x0
#define XPAR_USER_USER_INTC_IVAR_RST_VAL 0x10
#define XPAR_USER_USER_INTC_NUM_INTR_INPUTS 0x3
#define XPAR_USER_USER_INTC_ADDR_WIDTH 0x20
#define XPAR_USER_USER_INTC_NUM_SW_INTR 0x0
#define XPAR_USER_USER_INTC_HAS_IVR 0x1
#define XPAR_USER_USER_INTC_HAS_CIE 0x1
#define XPAR_USER_USER_INTC_HAS_SIE 0x1
#define XPAR_USER_USER_INTC_HAS_IPR 0x1

/* Canonical definitions for peripheral USER_USER_INTC */
#define XPAR_XINTC_0_BASEADDR 0x41800000
#define XPAR_XINTC_0_HIGHADDR 0x4180ffff
#define XPAR_XINTC_0_ADDR_WIDTH 0x20
#define XPAR_XINTC_0_COMPATIBLE "xlnx,axi-intc-4.1"
#define XPAR_XINTC_0_HAS_IVR 0x1
#define XPAR_XINTC_0_HAS_CIE 0x1
#define XPAR_XINTC_0_HAS_SIE 0x1
#define XPAR_XINTC_0_HAS_IPR 0x1
#define XPAR_XINTC_0_IS_FAST 0x0
#define XPAR_XINTC_0_IVAR_RST_VAL 0x10
#define XPAR_XINTC_0_KIND_OF_INTR 0x0
#define XPAR_XINTC_0_NUM_INTR_INPUTS 0x3
#define XPAR_XINTC_0_NUM_SW_INTR 0x0

#define XPAR_XQSPIPS_NUM_INSTANCES 1

/* Definitions for peripheral QSPI */
#define XPAR_QSPI_COMPATIBLE "xlnx,zynq-qspi-1.0"
#define XPAR_QSPI_BASEADDR 0xe000d000
#define XPAR_QSPI_HIGHADDR 0xe000dfff
#define XPAR_QSPI_CLOCK_FREQ 0xbebc200
#define XPAR_QSPI_CONNECTION_MODE 0x0
#define XPAR_QSPI_INTERRUPTS 0x4013
#define XPAR_QSPI_INTERRUPT_PARENT 0xf8f01000
#define XPAR_QSPI_QSPI_MODE 0x0
#define XPAR_QSPI_QSPI_BUS_WIDTH 0x2

/* Canonical definitions for peripheral QSPI */
#define XPAR_XQSPIPS_0_BASEADDR 0xe000d000
#define XPAR_XQSPIPS_0_HIGHADDR 0xe000dfff
#define XPAR_XQSPIPS_0_COMPATIBLE "xlnx,zynq-qspi-1.0"
#define XPAR_XQSPIPS_0_CLOCK_FREQ 0xbebc200
#define XPAR_XQSPIPS_0_CONNECTION_MODE 0x0
#define XPAR_XQSPIPS_0_INTERRUPTS 0x4013
#define XPAR_XQSPIPS_0_INTERRUPT_PARENT 0xf8f01000
#define XPAR_XQSPIPS_0_QSPI_MODE 0x0
#define XPAR_XQSPIPS_0_QSPI_BUS_WIDTH 0x2

#define XPAR_XSCUGIC_NUM_INSTANCES 1

/* Definitions for peripheral INTC */
#define XPAR_INTC_COMPATIBLE "arm,cortex-a9-gic"
#define XPAR_INTC_BASEADDR 0xf8f01000
#define XPAR_INTC_HIGHADDR 0xf8f01fff
#define XPAR_INTC_BASEADDR_1 0xf8f00100

/* Canonical definitions for peripheral INTC */
#define XPAR_XSCUGIC_0_BASEADDR 0xf8f01000
#define XPAR_XSCUGIC_0_HIGHADDR 0xf8f01fff
#define XPAR_XSCUGIC_0_COMPATIBLE "arm,cortex-a9-gic"

#define XPAR_XSCUTIMER_NUM_INSTANCES 1

/* Definitions for peripheral SCUTIMER */
#define XPAR_SCUTIMER_COMPATIBLE "arm,cortex-a9-twd-timer"
#define XPAR_SCUTIMER_BASEADDR 0xf8f00600
#define XPAR_SCUTIMER_HIGHADDR 0xf8f0061f
#define XPAR_SCUTIMER_INTERRUPTS 0x13100d
#define XPAR_SCUTIMER_INTERRUPT_PARENT 0xf8f01000

/* Canonical definitions for peripheral SCUTIMER */
#define XPAR_XSCUTIMER_0_BASEADDR 0xf8f00600
#define XPAR_XSCUTIMER_0_HIGHADDR 0xf8f0061f
#define XPAR_XSCUTIMER_0_COMPATIBLE "arm,cortex-a9-twd-timer"
#define XPAR_XSCUTIMER_0_INTERRUPTS 0x13100d
#define XPAR_XSCUTIMER_0_INTERRUPT_PARENT 0xf8f01000

#define XPAR_XSCUWDT_NUM_INSTANCES 1

/* Definitions for peripheral SCUWDT */
#define XPAR_SCUWDT_COMPATIBLE "xlnx,ps7-scuwdt-1.00.a"
#define XPAR_SCUWDT_BASEADDR 0xf8f00620
#define XPAR_SCUWDT_HIGHADDR 0xf8f006ff
#define XPAR_SCUWDT_INTERRUPTS 0x10400e
#define XPAR_SCUWDT_INTERRUPT_PARENT 0xf8f01000

/* Canonical definitions for peripheral SCUWDT */
#define XPAR_XSCUWDT_0_BASEADDR 0xf8f00620
#define XPAR_XSCUWDT_0_HIGHADDR 0xf8f006ff
#define XPAR_XSCUWDT_0_COMPATIBLE "xlnx,ps7-scuwdt-1.00.a"
#define XPAR_XSCUWDT_0_INTERRUPTS 0x10400e
#define XPAR_XSCUWDT_0_INTERRUPT_PARENT 0xf8f01000

#define XPAR_XSDPS_NUM_INSTANCES 1

/* Definitions for peripheral SDHCI0 */
#define XPAR_SDHCI0_COMPATIBLE "arasan,sdhci-8.9a"
#define XPAR_SDHCI0_BASEADDR 0xe0100000
#define XPAR_SDHCI0_HIGHADDR 0xe0100fff
#define XPAR_SDHCI0_SDIO_CLK_FREQ_HZ 0x2faf080
#define XPAR_SDHCI0_HAS_CD 0x1
#define XPAR_SDHCI0_HAS_WP 0x0
#define XPAR_SDHCI0_CLOCKS 0x15

/* Canonical definitions for peripheral SDHCI0 */
#define XPAR_XSDPS_0_BASEADDR 0xe0100000
#define XPAR_XSDPS_0_HIGHADDR 0xe0100fff
#define XPAR_XSDPS_0_COMPATIBLE "arasan,sdhci-8.9a"
#define XPAR_XSDPS_0_CLOCKS 0x15
#define XPAR_XSDPS_0_HAS_CD 0x1
#define XPAR_XSDPS_0_HAS_WP 0x0
#define XPAR_XSDPS_0_SDIO_CLK_FREQ_HZ 0x2faf080

#define XPAR_XSPIPS_NUM_INSTANCES 1

/* Definitions for peripheral SPI0 */
#define XPAR_SPI0_COMPATIBLE "xlnx,zynq-spi-r1p6"
#define XPAR_SPI0_BASEADDR 0xe0006000
#define XPAR_SPI0_HIGHADDR 0xe0006fff
#define XPAR_SPI0_SPI_CLK_FREQ_HZ 0x9ef21b0
#define XPAR_SPI0_INTERRUPTS 0x401a
#define XPAR_SPI0_INTERRUPT_PARENT 0xf8f01000

/* Canonical definitions for peripheral SPI0 */
#define XPAR_XSPIPS_0_BASEADDR 0xe0006000
#define XPAR_XSPIPS_0_HIGHADDR 0xe0006fff
#define XPAR_XSPIPS_0_COMPATIBLE "xlnx,zynq-spi-r1p6"
#define XPAR_XSPIPS_0_INTERRUPTS 0x401a
#define XPAR_XSPIPS_0_INTERRUPT_PARENT 0xf8f01000
#define XPAR_XSPIPS_0_SPI_CLK_FREQ_HZ 0x9ef21b0

#define XPAR_XSYSMON_NUM_INSTANCES 1

/* Definitions for peripheral XADC_WIZ_0 */
#define XPAR_XADC_WIZ_0_COMPATIBLE "xlnx,xadc-wiz-3.3"
#define XPAR_XADC_WIZ_0_BASEADDR 0x43c50000
#define XPAR_XADC_WIZ_0_HIGHADDR 0x43c5ffff
#define XPAR_XADC_WIZ_0_INCLUDE_INTR 0x1
#define XPAR_XADC_WIZ_0_IP_TYPE 0x0

/* Canonical definitions for peripheral XADC_WIZ_0 */
#define XPAR_XSYSMON_0_BASEADDR 0x43c50000
#define XPAR_XSYSMON_0_HIGHADDR 0x43c5ffff
#define XPAR_XSYSMON_0_COMPATIBLE "xlnx,xadc-wiz-3.3"
#define XPAR_XSYSMON_0_INCLUDE_INTR 0x1
#define XPAR_XSYSMON_0_IP_TYPE 0x0

#define XPAR_XTMRCTR_NUM_INSTANCES 3

/* Definitions for peripheral USER_AXI_TIMER_0 */
#define XPAR_USER_AXI_TIMER_0_COMPATIBLE "xlnx,axi-timer-2.0"
#define XPAR_USER_AXI_TIMER_0_BASEADDR 0x42800000
#define XPAR_USER_AXI_TIMER_0_HIGHADDR 0x4280ffff
#define XPAR_USER_AXI_TIMER_0_CLOCK_FREQUENCY "1e+08"
#define XPAR_USER_AXI_TIMER_0_INTERRUPTS 0x4021
#define XPAR_FABRIC_USER_AXI_TIMER_0_INTR 33
#define XPAR_USER_AXI_TIMER_0_INTERRUPT_PARENT 0xf8f01000

/* Canonical definitions for peripheral USER_AXI_TIMER_0 */
#define XPAR_XTMRCTR_0_BASEADDR 0x42800000
#define XPAR_FABRIC_XTMRCTR_0_INTR 33
#define XPAR_XTMRCTR_0_HIGHADDR 0x4280ffff
#define XPAR_XTMRCTR_0_COMPATIBLE "xlnx,axi-timer-2.0"
#define XPAR_XTMRCTR_0_CLOCK_FREQUENCY "1e+08"
#define XPAR_XTMRCTR_0_INTERRUPTS 0x4021
#define XPAR_XTMRCTR_0_INTERRUPT_PARENT 0xf8f01000

/* Definitions for peripheral USER_AXI_TIMER_1 */
#define XPAR_USER_AXI_TIMER_1_COMPATIBLE "xlnx,axi-timer-2.0"
#define XPAR_USER_AXI_TIMER_1_BASEADDR 0x42810000
#define XPAR_USER_AXI_TIMER_1_HIGHADDR 0x4281ffff
#define XPAR_USER_AXI_TIMER_1_CLOCK_FREQUENCY "1e+08"
#define XPAR_USER_AXI_TIMER_1_INTERRUPTS 0x4022
#define XPAR_FABRIC_USER_AXI_TIMER_1_INTR 34
#define XPAR_USER_AXI_TIMER_1_INTERRUPT_PARENT 0xf8f01000

/* Canonical definitions for peripheral USER_AXI_TIMER_1 */
#define XPAR_XTMRCTR_1_BASEADDR 0x42810000
#define XPAR_FABRIC_XTMRCTR_1_INTR 34
#define XPAR_XTMRCTR_1_HIGHADDR 0x4281ffff
#define XPAR_XTMRCTR_1_COMPATIBLE "xlnx,axi-timer-2.0"
#define XPAR_XTMRCTR_1_CLOCK_FREQUENCY "1e+08"
#define XPAR_XTMRCTR_1_INTERRUPTS 0x4022
#define XPAR_XTMRCTR_1_INTERRUPT_PARENT 0xf8f01000

/* Definitions for peripheral USER_AXI_TIMER_2 */
#define XPAR_USER_AXI_TIMER_2_COMPATIBLE "xlnx,axi-timer-2.0"
#define XPAR_USER_AXI_TIMER_2_BASEADDR 0x42820000
#define XPAR_USER_AXI_TIMER_2_HIGHADDR 0x4282ffff
#define XPAR_USER_AXI_TIMER_2_CLOCK_FREQUENCY "1e+08"
#define XPAR_USER_AXI_TIMER_2_INTERRUPTS 0x4023
#define XPAR_FABRIC_USER_AXI_TIMER_2_INTR 35
#define XPAR_USER_AXI_TIMER_2_INTERRUPT_PARENT 0xf8f01000

/* Canonical definitions for peripheral USER_AXI_TIMER_2 */
#define XPAR_XTMRCTR_2_BASEADDR 0x42820000
#define XPAR_FABRIC_XTMRCTR_2_INTR 35
#define XPAR_XTMRCTR_2_HIGHADDR 0x4282ffff
#define XPAR_XTMRCTR_2_COMPATIBLE "xlnx,axi-timer-2.0"
#define XPAR_XTMRCTR_2_CLOCK_FREQUENCY "1e+08"
#define XPAR_XTMRCTR_2_INTERRUPTS 0x4023
#define XPAR_XTMRCTR_2_INTERRUPT_PARENT 0xf8f01000

#define XPAR_XUARTLITE_NUM_INSTANCES 1

/* Definitions for peripheral AXI_UARTLITE_0 */
#define XPAR_AXI_UARTLITE_0_COMPATIBLE "xlnx,axi-uartlite-2.0"
#define XPAR_AXI_UARTLITE_0_BASEADDR 0x42c00000
#define XPAR_AXI_UARTLITE_0_HIGHADDR 0x42c0ffff
#define XPAR_AXI_UARTLITE_0_BAUDRATE 0x2580
#define XPAR_AXI_UARTLITE_0_USE_PARITY 0x0
#define XPAR_AXI_UARTLITE_0_ODD_PARITY 0x0
#define XPAR_AXI_UARTLITE_0_DATA_BITS 0x8
#define XPAR_AXI_UARTLITE_0_INTERRUPTS 0x1034
#define XPAR_FABRIC_AXI_UARTLITE_0_INTR 52
#define XPAR_AXI_UARTLITE_0_INTERRUPT_PARENT 0xf8f01000

/* Canonical definitions for peripheral AXI_UARTLITE_0 */
#define XPAR_XUARTLITE_0_BASEADDR 0x42c00000
#define XPAR_FABRIC_XUARTLITE_0_INTR 52
#define XPAR_XUARTLITE_0_HIGHADDR 0x42c0ffff
#define XPAR_XUARTLITE_0_BAUDRATE 0x2580
#define XPAR_XUARTLITE_0_COMPATIBLE "xlnx,axi-uartlite-2.0"
#define XPAR_XUARTLITE_0_DATA_BITS 0x8
#define XPAR_XUARTLITE_0_INTERRUPTS 0x1034
#define XPAR_XUARTLITE_0_INTERRUPT_PARENT 0xf8f01000
#define XPAR_XUARTLITE_0_ODD_PARITY 0x0
#define XPAR_XUARTLITE_0_USE_PARITY 0x0

#define XPAR_XUARTPS_NUM_INSTANCES 1

/* Definitions for peripheral UART0 */
#define XPAR_UART0_COMPATIBLE "xlnx,xuartps"
#define XPAR_UART0_BASEADDR 0xe0000000
#define XPAR_UART0_HIGHADDR 0xe0000fff
#define XPAR_UART0_CLOCK_FREQ 0x5f5e100
#define XPAR_UART0_HAS_MODEM 0x0
#define XPAR_UART0_CLOCKS 0x17
#define XPAR_UART0_INTERRUPTS 0x401b
#define XPAR_UART0_INTERRUPT_PARENT 0xf8f01000

/* Canonical definitions for peripheral UART0 */
#define XPAR_XUARTPS_0_BASEADDR 0xe0000000
#define XPAR_XUARTPS_0_HIGHADDR 0xe0000fff
#define XPAR_XUARTPS_0_COMPATIBLE "xlnx,xuartps"
#define XPAR_XUARTPS_0_CLOCK_FREQ 0x5f5e100
#define XPAR_XUARTPS_0_CLOCKS 0x17
#define XPAR_XUARTPS_0_HAS_MODEM 0x0
#define XPAR_XUARTPS_0_INTERRUPTS 0x401b
#define XPAR_XUARTPS_0_INTERRUPT_PARENT 0xf8f01000

#define XPAR_XUSBPS_NUM_INSTANCES 1

/* Definitions for peripheral USB0 */
#define XPAR_USB0_COMPATIBLE "xlnx,zynq-usb-2.20a"
#define XPAR_USB0_BASEADDR 0xe0002000
#define XPAR_USB0_HIGHADDR 0xe0002fff
#define XPAR_USB0_INTERRUPTS 0x4015
#define XPAR_USB0_INTERRUPT_PARENT 0xf8f01000

/* Canonical definitions for peripheral USB0 */
#define XPAR_XUSBPS_0_BASEADDR 0xe0002000
#define XPAR_XUSBPS_0_HIGHADDR 0xe0002fff
#define XPAR_XUSBPS_0_COMPATIBLE "xlnx,zynq-usb-2.20a"
#define XPAR_XUSBPS_0_INTERRUPTS 0x4015
#define XPAR_XUSBPS_0_INTERRUPT_PARENT 0xf8f01000

#define XPAR_XVTC_NUM_INSTANCES 1

/* Definitions for peripheral VIDEO_VTC_OUT */
#define XPAR_VIDEO_VTC_OUT_COMPATIBLE "xlnx,v-tc-6.2"
#define XPAR_VIDEO_VTC_OUT_BASEADDR 0x43c20000
#define XPAR_VIDEO_VTC_OUT_HIGHADDR 0x43c2ffff

/* Canonical definitions for peripheral VIDEO_VTC_OUT */
#define XPAR_XVTC_0_BASEADDR 0x43c20000
#define XPAR_XVTC_0_HIGHADDR 0x43c2ffff
#define XPAR_XVTC_0_COMPATIBLE "xlnx,v-tc-6.2"

#define XPAR_XXADCPS_NUM_INSTANCES 1

/* Definitions for peripheral ADC */
#define XPAR_ADC_COMPATIBLE "xlnx,zynq-xadc-1.00.a"
#define XPAR_ADC_BASEADDR 0xf8007100
#define XPAR_ADC_HIGHADDR 0xf800711f

/* Canonical definitions for peripheral ADC */
#define XPAR_XXADCPS_0_BASEADDR 0xf8007100
#define XPAR_XXADCPS_0_HIGHADDR 0xf800711f
#define XPAR_XXADCPS_0_COMPATIBLE "xlnx,zynq-xadc-1.00.a"

/* Definitions for peripheral L2 */
#define XPAR_L2_BASEADDR 0xf8f02000
#define XPAR_L2_HIGHADDR 0xf8f02fff

/* Canonical definitions for peripheral L2 */
#define XPAR_PS7_PL310_0_BASEADDR 0xf8f02000
#define XPAR_PS7_PL310_0_HIGHADDR 0xf8f02fff

/* Definitions for peripheral MC */
#define XPAR_MC_BASEADDR 0xf8006000
#define XPAR_MC_HIGHADDR 0xf8006fff

/* Canonical definitions for peripheral MC */
#define XPAR_PS7_DDRC_0_BASEADDR 0xf8006000
#define XPAR_PS7_DDRC_0_HIGHADDR 0xf8006fff

/* Definitions for peripheral SLCR */
#define XPAR_SLCR_BASEADDR 0xf8000000
#define XPAR_SLCR_HIGHADDR 0xf8000fff

/* Canonical definitions for peripheral SLCR */
#define XPAR_PS7_SLCR_0_BASEADDR 0xf8000000
#define XPAR_PS7_SLCR_0_HIGHADDR 0xf8000fff

/* Definitions for peripheral GLOBAL_TIMER */
#define XPAR_GLOBAL_TIMER_BASEADDR 0xf8f00200
#define XPAR_GLOBAL_TIMER_HIGHADDR 0xf8f0021f

/* Canonical definitions for peripheral GLOBAL_TIMER */
#define XPAR_PS7_GLOBALTIMER_0_BASEADDR 0xf8f00200
#define XPAR_PS7_GLOBALTIMER_0_HIGHADDR 0xf8f0021f

/* Definitions for peripheral PS7_PMU_0 */
#define XPAR_PS7_PMU_0_BASEADDR 0xf8891000
#define XPAR_PS7_PMU_0_HIGHADDR 0xf8891fff

/* Definitions for peripheral PS7_OCMC_0 */
#define XPAR_PS7_OCMC_0_BASEADDR 0xf800c000
#define XPAR_PS7_OCMC_0_HIGHADDR 0xf800cfff

/* Definitions for peripheral PS7_GPV_0 */
#define XPAR_PS7_GPV_0_BASEADDR 0xf8900000
#define XPAR_PS7_GPV_0_HIGHADDR 0xf89fffff

/* Definitions for peripheral PS7_SCUC_0 */
#define XPAR_PS7_SCUC_0_BASEADDR 0xf8f00000
#define XPAR_PS7_SCUC_0_HIGHADDR 0xf8f000fc

/* Definitions for peripheral PS7_IOP_BUS_CONFIG_0 */
#define XPAR_PS7_IOP_BUS_CONFIG_0_BASEADDR 0xe0200000
#define XPAR_PS7_IOP_BUS_CONFIG_0_HIGHADDR 0xe0200fff

/* Definitions for peripheral PS7_DMA_NS */
#define XPAR_PS7_DMA_NS_BASEADDR 0xf8004000
#define XPAR_PS7_DMA_NS_HIGHADDR 0xf8004fff

/* Canonical definitions for peripheral PS7_DMA_NS */
#define XPAR_PS7_DMA_0_BASEADDR 0xf8004000
#define XPAR_PS7_DMA_0_HIGHADDR 0xf8004fff

/* Definitions for peripheral PS7_AFI_0 */
#define XPAR_PS7_AFI_0_BASEADDR 0xf8008000
#define XPAR_PS7_AFI_0_HIGHADDR 0xf8008fff

/* Definitions for peripheral PS7_AFI_1 */
#define XPAR_PS7_AFI_1_BASEADDR 0xf8009000
#define XPAR_PS7_AFI_1_HIGHADDR 0xf8009fff

/* Definitions for peripheral PS7_AFI_2 */
#define XPAR_PS7_AFI_2_BASEADDR 0xf800a000
#define XPAR_PS7_AFI_2_HIGHADDR 0xf800afff

/* Definitions for peripheral PS7_AFI_3 */
#define XPAR_PS7_AFI_3_BASEADDR 0xf800b000
#define XPAR_PS7_AFI_3_HIGHADDR 0xf800bfff

/* Definitions for peripheral AUDIO_AUDIO_CODEC_CTRL_0 */
#define XPAR_AUDIO_AUDIO_CODEC_CTRL_0_BASEADDR 0x43c00000
#define XPAR_AUDIO_AUDIO_CODEC_CTRL_0_HIGHADDR 0x43c0ffff

/* Canonical definitions for peripheral AUDIO_AUDIO_CODEC_CTRL_0 */
#define XPAR_AUDIO_CODEC_CTRL_0_BASEADDR 0x43c00000
#define XPAR_AUDIO_CODEC_CTRL_0_HIGHADDR 0x43c0ffff

/* Definitions for peripheral BUCK_CONTROLLER_0 */
#define XPAR_BUCK_CONTROLLER_0_BASEADDR 0x43c60000
#define XPAR_BUCK_CONTROLLER_0_HIGHADDR 0x43c6ffff

/* Definitions for peripheral ULTRASONE_0 */
#define XPAR_ULTRASONE_0_BASEADDR 0x43c70000
#define XPAR_ULTRASONE_0_HIGHADDR 0x43c7ffff

/* Definitions for peripheral VIDEO_AXI_DYNCLK */
#define XPAR_VIDEO_AXI_DYNCLK_BASEADDR 0x43c10000
#define XPAR_VIDEO_AXI_DYNCLK_HIGHADDR 0x43c1ffff

/* Canonical definitions for peripheral VIDEO_AXI_DYNCLK */
#define XPAR_AXI_DYNCLK_0_BASEADDR 0x43c10000
#define XPAR_AXI_DYNCLK_0_HIGHADDR 0x43c1ffff

/* Definitions for peripheral LCD_CONTROLLER_0 */
#define XPAR_LCD_CONTROLLER_0_BASEADDR 0x43c30000
#define XPAR_LCD_CONTROLLER_0_HIGHADDR 0x43c3ffff

/* Definitions for peripheral MODULATOR_AXI_IP_G_0 */
#define XPAR_MODULATOR_AXI_IP_G_0_BASEADDR 0x43c40000
#define XPAR_MODULATOR_AXI_IP_G_0_HIGHADDR 0x43c4ffff

#define XPAR_PS7_DDR_0_BASEADDRESS 0x100000
#define XPAR_PS7_DDR_0_HIGHADDRESS 0x1fffffff
#define XPAR_PS7_QSPI_LINEAR_0_BASEADDRESS 0xfc000000
#define XPAR_PS7_QSPI_LINEAR_0_HIGHADDRESS 0xfcffffff
#define XPAR_PS7_RAM_0_BASEADDRESS 0x0
#define XPAR_PS7_RAM_0_HIGHADDRESS 0x2ffff
#define XPAR_PS7_RAM_1_BASEADDRESS 0xffff0000
#define XPAR_PS7_RAM_1_HIGHADDRESS 0xfffffdff
#define XPAR_CPU_CORE_CLOCK_FREQ_HZ 650000000

#define XPAR_CPU_TIMESTAMP_CLK_FREQ 0

/* Number of SLRs */
#define NUMBER_OF_SLRS 0x1

/* Device ID */
#define XPAR_DEVICE_ID "7z020"

#endif  /* end of protection macro */